### ISSUE TITLE
List up and Decide on mods for this round

### ISSUE THREAD

**Issue by aptlyundecided** [aptlyundecided/factorio-#1]
Below we should list up the mods

**Comment by aptlyundecided** [comment]
### What I have listed so far from our conversation
- Aircraft
- Bio-industries
- Fully Automated Rail Layer  
- The FAT Controller  
- Squeak Through (useful for squeezing between buildings)  
- Robot army (for mobile defense of expansions)

**Comment by aptlyundecided** [comment]
### More
- Logistic Train Network
- Angels Add Ons - Pressure Tanks
- KS power
- Smart Trains  
- Repair Turrets

**Comment by aptlyundecided** [comment]
### More  
- Repair Turrets  
- [Bobs Logistics](https://mods.factorio.com/mod/boblogistics)
- [Bobs Power](https://mods.factorio.com/mod/bobpower)
- [Bobs adjustable inserters](https://mods.factorio.com/mod/bobinserters)

**Comment by aptlyundecided** [comment]
### Bobs Mods
- Bobs Mining
- Bobs Modules  
- Bobs Greenhouse Mod  
- Bobs Vehicle Equipment  
- [Bobs Logistics](https://mods.factorio.com/mod/boblogistics)
- [Bobs Power](https://mods.factorio.com/mod/bobpower)
- [Bobs adjustable inserters](https://mods.factorio.com/mod/bobinserters)

**Comment by aptlyundecided** [comment]
- Long Reach
- Factorissimo 2
- Angels Add-ons Warehouses

**Comment by N05H** [comment]
I see, I see....
Ssssss............ So.
Remembering from last time: "Zu viel des Guten!".
We do not want to use to many modes -> overkill.
<br/><br/>
### The mods we used last time were:
   - boblibrary
   - boblogistic
   - bobmining
   - bobpower
   - bobtech
   - bobvehicleequipment


### Your requests were:

**Markus:**
   - Aircraft
   - Bio Industry

**Alex:**
   - Factorissimo 2
   - FAT Controller


I looked into the ones listed above and i really like "Repair Turret".
Just because nobody likes to do that later!

"Squeack Trough" is very useful too and doesn't impact the game at all except making us move smoother!

"KS Power" gives us more options for power supply.


**That being said, Chris:**
   - Repair Turret
   - Squeack Through
   - KS Power

<br/><br/>
Assuming everybody is ok with the Bobs mod we used before, we have a final mod list and can start the server.
Confirmation appreciated.
<br/><br/>
I dont think its too much, but still a decent change.

### Final list:
   - boblibrary
   - boblogistic
   - bobmining
   - bobpower
   - bobtech
   - bobvehicleequipment
   - Aircraft
   - Bio Industry
   - Factorissimo 2
   - FAT Controller
   - Repair Turret
   - Squeack Through
   - KS Power

**Comment by aptlyundecided** [comment]
I approve!

**Comment by aptlyundecided** [comment]
WAIT!

We need one train advancement

**Comment by aptlyundecided** [comment]
- FARL
- The FAT Controller
- Logistic Train Network  
- Smart Trains

We need at least one

**Comment by N05H** [comment]
List updated with FAT Controller

**Comment by N05H** [comment]
List updated with:
   - Bobs personal equipment
   - Power and Armor

**Comment by N05H** [comment]
### So, the modes on the server are:

1. [Aircraft](https://mods.factorio.com/download/Aircraft/5d5dafd708407a000d7e68e0)
2. [BioIndustry](https://mods.factorio.com/download/Bio_Industries/5d73de544b9e53000d18830c)
3. [BobEquipment](https://mods.factorio.com/download/bobequipment/5ce1d23dcc3d86000d2eb7c4)
4. [BobLibrary](https://mods.factorio.com/download/boblibrary/5d1102d3eed144000cc8edf0)
5. [BobLogistics](https://mods.factorio.com/download/boblogistics/5d6eceb7df0937000b874b81)
6. [BobMining](https://mods.factorio.com/download/bobmining/5d15343092a82b000cded1c9)
7. [BobModules](https://mods.factorio.com/download/bobmodules/5cdee1237b286b000c59a779)
8. [BobPower](https://mods.factorio.com/download/bobpower/5d1690d94ebe080032c474ff)
9. [BobTech](https://mods.factorio.com/download/bobtech/5d153497579041000cd5cec1)
10. [BobVehicleEquipment](https://mods.factorio.com/download/bobvehicleequipment/5d081b6cc6df2f000c446eeb)
11. [Factorissimo2](https://mods.factorio.com/download/Factorissimo2/5d52e682bbf501000cb35a4c)
12. [KSPower](https://mods.factorio.com/download/KS_Power/5c8e9c16e687c0000b9d591d)
13. [PowerAndArmor](https://mods.factorio.com/download/PowerAndArmor/5ce579381edd28000b3ab2dd)
14. [RepairTurret](https://mods.factorio.com/download/Repair_Turret/5d8a23b6392413000c7cd2b0)
15. [SqueakThrough](https://mods.factorio.com/download/Squeak%20Through/5c777b28bc05f7000c2895fa)
16. [FATController](https://mods.factorio.com/download/TheFatController/5d83e2bdc93091000c57693d)
17. [BobAssembly](https://mods.factorio.com/download/bobassembly/5d6ece9274e99c000b750f17)
18. [BobInserters](https://mods.factorio.com/download/bobinserters/5d4c52ac7a5959000c447893)
19. [BobWarfar](https://mods.factorio.com/download/bobwarfare/5d4c53253fac7d000b1b132c)

**Comment by aptlyundecided** [comment]
This was totally not even needed!
